// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwjMbKnKJRAm-MNt1HcW9WpLhVjb-3FM',
    appId: '1:1093298457435:ios:5aa3108734e5b7b2bc687e',
    messagingSenderId: '1093298457435',
    projectId: 'toeiceggadmin',
    storageBucket: 'toeiceggadmin.firebasestorage.app',
    iosBundleId: 'com.example.eggToeic',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14bHCgPfoYvvuY6okqRvYl08UaWangdc',
    appId: '1:1093298457435:android:5d89886038353650bc687e',
    messagingSenderId: '1093298457435',
    projectId: 'toeiceggadmin',
    storageBucket: 'toeiceggadmin.firebasestorage.app',
  );

}