// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9WpvkEuY3F4-D4mjXqdNIaWt9V2zO5FM',
    appId: '1:460976305272:web:1284101687ae54a4df298d',
    messagingSenderId: '460976305272',
    projectId: 'eggtoeic-9c88f',
    authDomain: 'eggtoeic-9c88f.firebaseapp.com',
    storageBucket: 'eggtoeic-9c88f.firebasestorage.app',
    measurementId: 'G-05GDE4JCF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hrgT7uGsTE_R35cMFFHrD3_wkMcKa4U',
    appId: '1:460976305272:android:b3054ca1e5c4dad0df298d',
    messagingSenderId: '460976305272',
    projectId: 'eggtoeic-9c88f',
    storageBucket: 'eggtoeic-9c88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3B76Ts5GAt64d3vByehgYmj94SQyJLc',
    appId: '1:460976305272:ios:0600d9b502cc7870df298d',
    messagingSenderId: '460976305272',
    projectId: 'eggtoeic-9c88f',
    storageBucket: 'eggtoeic-9c88f.firebasestorage.app',
    iosBundleId: 'com.example.eggToeic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN3B76Ts5GAt64d3vByehgYmj94SQyJLc',
    appId: '1:460976305272:ios:0600d9b502cc7870df298d',
    messagingSenderId: '460976305272',
    projectId: 'eggtoeic-9c88f',
    storageBucket: 'eggtoeic-9c88f.firebasestorage.app',
    iosBundleId: 'com.example.eggToeic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9WpvkEuY3F4-D4mjXqdNIaWt9V2zO5FM',
    appId: '1:460976305272:web:67130e0ff9d602bbdf298d',
    messagingSenderId: '460976305272',
    projectId: 'eggtoeic-9c88f',
    authDomain: 'eggtoeic-9c88f.firebaseapp.com',
    storageBucket: 'eggtoeic-9c88f.firebasestorage.app',
    measurementId: 'G-VN5JH0RXR7',
  );
}
